### PR TITLE
Fix remove Deprecated android beam in Android 14

### PR DESCRIPTION
**Pull request by souleymane-diallo**
> Removal of Deprecated Android Beam Features in API 34

  The chariotsolutions/phonegap-nfc plugin includes Android Beam features, which were deprecated in Android API 29 and 
  removed in API 34. As a result, the plugin is incompatible with Android 14.

* To fix this, I removed the nfc.share, nfc.unshare, nfc.handover, and nfc.stopHandover functions from the NfcPlugin.java file.
* The nfc.handover and nfc.stopHandover methods, specific to Android only, have also been removed from the JavaScript file 
   phonegap-nfc.js and README

Files modified:
  * NfcPlugin.java
  * phonegap-nfc.js
  * README.md

### CODE REVIEW

**Comment by pierresh** [comment]
Hello,

Yes, I also met that problem. It would be great that this PR gets merged :)

**Comment by ath0mas** [comment]
Planning to do it soon yes.

**Comment by ath0mas** [comment]
Closing this PR, to check and discuss the changes directly in parent repo and PR https://github.com/chariotsolutions/phonegap-nfc/pull/508.
When ok for me, I'll do the PR here and merge, before a new release to follow quickly.

**Comment by ath0mas** [comment]
Released in [v1.3.0-5](https://github.com/ns0m/cordova-plugin-ns0m-nfc/releases/tag/v1.3.0-5), published to [cordova-plugin-ns0m-nfc](https://www.npmjs.com/package/cordova-plugin-ns0m-nfc).
Thanks again!

**Pull request closed without merging**
